server:
  error:
    whitelabel:
        enabled: False
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/mydb?useSSL=false
      username: root
      password: 123456
      

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
       strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id:
          new_generator_mappings: false
        format_sql: true   
               